### ISSUE TITLE
OMG!!Are all the apis destroyed? I can't get the balance even

### ISSUE THREAD

**Issue by ztlovemst11** [sporestack/bitcash#24]
Traceback (most recent call last):
  File "E:/zt_6.27/py2/testBCH6.py", line 8, in <module>
    print(key.get_unspents())
  File "E:\zt_6.27\python\lib\site-packages\bitcash\wallet.py", line 489, in get_unspents
    self.unspents[:] = NetworkAPI.get_unspent_testnet(self.address)
  File "E:\zt_6.27\python\lib\site-packages\bitcash\network\services.py", line 319, in get_unspent_testnet
    raise ConnectionError('All APIs are unreachable.')
ConnectionError: All APIs are unreachable.

**Comment by ztlovemst11** [comment]
testnet api has expired!!!please update

**Comment by teran-mckinney** [comment]
Can you investigate this? Can you find another testnet API? Maybe it's just down for a little while.

I'll check later. I generally use mainnet, but I agree that testnet should be working.

**Comment by ztlovemst11** [comment]
I am very sorry about this, the test network is not smooth now, maybe I should go to the main network test
